### ISSUE TITLE
How to save params so that I can decode the file in another projects?

### ISSUE THREAD

**Issue by Edwardmark** [kulkarniamit/openssl-evp-demo#1]
How to save params so that I can decode the file in another projects?
I see the important thing that can decode and encode file is the params, so how to save it so that I can encode file in one projects and decode it in another?
Thanks.

**Comment by kulkarniamit** [comment]
Could you be more specific about the parameters you wish to save for encryption/decryption across projects? What kind of parameters would you like to save?

**Comment by Edwardmark** [comment]
@kulkarniamit Let me put is this way. I want encrypr one file using the password, I sent the encrypted file to my friends and he has the password to decrypt it. 
So how to save the password, which is the params *key, *iv.
```
 typedef struct _cipher_params_t{
    unsigned char *key;
    unsigned char *iv;
    unsigned int encrypt;
    const EVP_CIPHER *cipher_type;
}cipher_params_t;
```

**Comment by kulkarniamit** [comment]
The program is primarily intended to demonstrate the use of EVP functions and hence uses a randomly generated key and IV.
In order to use the program for your use case, I think you should use a password based derivation routine like [PKCS5_PBKDF2_HMAC](https://www.openssl.org/docs/man1.1.0/man3/PKCS5_PBKDF2_HMAC_SHA1.html). Depending on the OpenSSL version, you can choose from these [EVP Key Derivation](https://wiki.openssl.org/index.php/EVP_Key_Derivation) functions. Your program can take this passphrase as a command line argument. The program needs to be modified to accept a passphrase and an argument to encrypt/decrypt using the passphrase.

One way of sharing your passphrase is by using public key cryptography. Your passphrase can be used to encrypt the file and your passphrase can be encrypted using your friend's public key. If your encrypted passphrase and encrypted file are shared, your friend can use his/her corresponding private key to decrypt the passphrase and use it as input to the program and decrypt the file.

* Friend creates a public-private key pair using `ssh-keygen`
```
$ ssh-keygen -m pem -f /tmp/id_rsa -t rsa -N ""
Generating public/private rsa key pair.
Your identification has been saved in /tmp/id_rsa.
Your public key has been saved in /tmp/id_rsa.pub.
The key fingerprint is:
...
```

* Friend exports public key to pkcs8 format (required by openssl)
```
$ ssh-keygen -e -f /tmp/id_rsa.pub -m pkcs8 > /tmp/id_rsa.pub.pkcs8
```
* `/tmp/id_rsa.pub.pkcs8` is shared with you 
* Encrypt the file using a passphrase and encrypt the passphrase using friend's public key

```
$ ./program --encrypt -p passphrase.txt -i <input-file> -o <encrypted-file>
$ openssl rsautl -encrypt -pubin -inkey /tmp/id_rsa.pub.pkcs8 -in passphrase.txt -out encrypted-passphrase
```

* Share `encrypted-passphrase` and `<encrypted-file>` with friend
* Friend will use private key to decrypt the encrypted passphrase and use the passphrase to decrypt the file 
```
$ openssl rsautl -decrypt -ssl -inkey /tmp/id_rsa -in encrypted-passphrase -out decrypted-passphrase -pkcs

$ ./program --decrypt -p decrypted-passphrase -i <encrypted-file> -o <decrypted-file>
```

**Comment by Edwardmark** [comment]
@kulkarniamit Thanks. It really helps.
Best, 
Edward.
